=== mdturnerinoz/bin-cmds/editix/samples/xml/personal.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="personnel">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" minOccurs="1" ref="person"/>
			</xsd:sequence>
		</xsd:complexType>
		<xsd:unique name="unique1">
			<xsd:selector xpath="person"/>
			<xsd:field xpath="name/given"/>
			<xsd:field xpath="name/family"/>
		</xsd:unique>
		<xsd:key name="empid">
			<xsd:selector xpath="person"/>
			<xsd:field xpath="@id"/>
		</xsd:key>
		<xsd:keyref name="keyref1" refer="empid">
			<xsd:selector xpath="person"/>
			<xsd:field xpath="link/@manager"/>
		</xsd:keyref>
	</xsd:element>
	<xsd:element name="person">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="name"/>
				<xsd:element maxOccurs="unbounded" minOccurs="0" ref="email"/>
				<xsd:element maxOccurs="unbounded" minOccurs="0" ref="url"/>
				<xsd:element maxOccurs="1" minOccurs="0" ref="link"/>
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:ID" use="required"/>
			<xsd:attribute name="note" type="xsd:string"/>
			<xsd:attribute default="false" name="contr">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="true"/>
						<xsd:enumeration value="false"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="salary" type="xsd:integer"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="name">
		<xsd:complexType>
			<xsd:all>
				<xsd:element ref="family"/>
				<xsd:element ref="given"/>
			</xsd:all>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="family" type="xsd:string"/>
	<xsd:element name="given" type="xsd:string"/>
	<xsd:element name="email" type="xsd:string"/>
	<xsd:element name="url">
		<xsd:complexType>
			<xsd:attribute default="http://" name="href" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="link">
		<xsd:complexType>
			<xsd:attribute name="manager" type="xsd:IDREF"/>
			<xsd:attribute name="subordinates" type="xsd:IDREFS"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:notation name="gif" public="-//APP/Photoshop/4.0" system="photoshop.exe"/>
</xsd:schema>

=== mdturnerinoz/bin-cmds/editix/samples/xml/personal.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- You can switch to the Visual Editor -->

<?xml-stylesheet type="text/css" href="personal.css"?>

<personnel xsi:noNamespaceSchemaLocation="personal.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<person contr="false" id="Big.Boss">
		<name>
			<family>Boss</family>
			<given>Great</given>
		</name>
		<email>bossdd@foo.com</email>
		<link subordinates="one.worker two.worker three.worker four.worker five.worker"/>
	</person>
	<person contr="false" id="one.worker">
		<name>
			<family>Worker 1</family>
			<given>One</given>
		</name>
		<email>one@fdddddsddddoo.com</email>
		<link manager="Big.Boss"/>
	</person>
	<person contr="false" id="two.worker">
		<name>
			<family>Worker 2</family>
			<given>Two</given>
		</name>
		
		<email>two@foo.com</email>
		<link manager="Big.Boss"/>
	</person>
	<person contr="false" id="three.worker">
		<name>
			<family>Worker 3</family>
			<given>Three</given>
		</name>
		<email>three@foo.com</email>
		<link manager="Big.Boss"/>
	</person>
	<person contr="false" id="four.worker">
		<name>
			<family>Worker 4</family>
			<given>Four</given>
		</name>
		<email>four@foo.com</email>
		<link manager="Big.Boss"/>
	</person>
	<person contr="false" id="five.worker">
		<name>
			<family>Worker 5</family>
			<given>Five</given>
		</name>
		<email>five@foo.com</email>
		<link manager="Big.Boss"/>
	</person>
</personnel>
